### ISSUE TITLE
TypeError: Cannot read property '_' of undefined

### ISSUE THREAD

**Issue by krainboltgreene** [yaymukund/grunt-ember-handlebars#4]
The error from running `grunt`:

```
Running "ember_handlebars:all" (ember_handlebars) task

TypeError: Cannot read property '_' of undefined
    at Object.module.exports (/Users/krainboltgreene/Code/ruby/absolvte/public/node_modules/grunt-ember-handlebars/tasks/ember-handlebars.js:29:15)
    at Object.task.registerMultiTask.thisTask (/Users/krainboltgreene/Code/ruby/absolvte/public/node_modules/grunt/lib/grunt/task.js:109:15)
    at Object.task.registerTask.thisTask.fn (/Users/krainboltgreene/Code/ruby/absolvte/public/node_modules/grunt/lib/grunt/task.js:58:16)
    at Task.<anonymous> (/Users/krainboltgreene/Code/ruby/absolvte/public/node_modules/grunt/lib/util/task.js:343:36)
    at Task.<anonymous> (/Users/krainboltgreene/Code/ruby/absolvte/public/node_modules/grunt/lib/util/task.js:319:9)
    at Task.<anonymous> (/Users/krainboltgreene/Code/ruby/absolvte/public/node_modules/grunt/lib/util/task.js:346:11)
    at Task.<anonymous> (/Users/krainboltgreene/Code/ruby/absolvte/public/node_modules/grunt/lib/util/task.js:319:9)
    at module.exports.grunt.registerHelper.grunt.utils.spawn.cmd (/Users/krainboltgreene/Code/ruby/absolvte/public/node_modules/grunt/tasks/qunit.js:223:7)
    at Object.async.forEachSeries (/Users/krainboltgreene/Code/ruby/absolvte/public/node_modules/grunt/node_modules/async/lib/async.js:104:20)
    at Object.module.exports.grunt.registerHelper.grunt.utils.spawn.cmd (/Users/krainboltgreene/Code/ruby/absolvte/public/node_modules/grunt/tasks/qunit.js:130:23)
```

**Comment by krainboltgreene** [comment]
Turns out this is because of changes to use the Grunt 0.4 interface? Grunt.js 0.4 isn't even out yet! Why would you break for anyone attempting to use the available Grunt.js version?!

**Comment by yaymukund** [comment]
Hi, thanks for the issue report.

You're welcome to [use version 0.1.x for grunt 0.3.x compatibility](https://github.com/yaymukund/grunt-ember-handlebars#updating-from-01x-to-02x). If the docs and source aren't enough, I've always found the Grunt IRC channel (freenode#grunt) to be very helpful.

**Comment by krainboltgreene** [comment]
It would have to have the released version of this package actually work with the released version of it's dependency.

It seems odd that you would release a version that is broken.
